replicaCount: 3

image:
  repository: ghcr.io/bonanoel/pong
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets:
  name: ghcr-secret

appName: pong
nameSpace: app-service
hosts:
  - pong.app.kind.org

gateway:
  enabled: true
  port: 80

virtualService:
  enabled: true
  port: 80

destinationRule:
  enabled: true
  loadBalancer:
    policy: RANDOM

redis:
  enabled: true
  image:
    repository: redis
    tag: "latest"
  service:
    port: 6379
  resources: {}
