replicaCount: 1

image:
  repository: ghcr.io/bonanoel/dateresponder
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

appName: dateresponder
nameSpace: app-service
hosts:
  - dateresponder.app.kind.org

gateway:
  enabled: true
  port: 80

virtualService:
  enabled: true
  port: 80
