replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

appName: dateresponder
nameSpace: app-service
hosts:
  - date-responder.app.kind.org

gateway:
  enabled: true
  port: 80

virtualService:
  enabled: true
  port: 80
