replicaCount: 1

image:
  repository: ghcr.io/bonanoel/datecaller
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

appName: datecaller
nameSpace: app-ui
hosts:
  - datecaller.app.kind.org

gateway:
  enabled: true
  port: 80

virtualService:
  enabled: true
  port: 8088
