{{- if .Values.gateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.appName}}
  namespace: {{ .Values.nameSpace }}
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
  - hosts:
    - {{ .Values.hosts | join "\n    - " }}
    - port:
        number: {{ .Values.gateway.port }}
        name: http
        protocol: HTTP
{{- end }}