name: Build and Push Datecaller and Dateresponder Docker Images

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [datecaller, dateresponder]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set lowercase owner name
      run: echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
      env:
        OWNER: '${{ github.repository_owner }}'

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCP_PAT }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./${{ matrix.service }}
        push: true
        tags: ghcr.io/${{ env.OWNER_LC }}/${{ matrix.service }}:latest

    - name: Logout from GitHub Container Registry
      run: docker logout ghcr.io

    - name: Set image to public
      env:
        GITHUB_TOKEN: ${{ secrets.GHCP_PAT }}
      run: |
        gh api \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          "/user/packages/container/${{ env.OWNER_LC }}/${{ matrix.service }}/visibility" \
          -f visibility=public